### PR TITLE
Reorganisation before arxiv submission

### PR DESCRIPTION
**Pull request by drphilmarshall**
Still to do:
- [x] Update README to reflect "as-is" unsupported code release
- [x] Provide hyperlinks to Auger papers in README
- [x] Add header to all code files listing license and citation instructions.
- [ ] Get group to sign off 
- [ ] Merge this pull request

### CODE REVIEW

**Comment by drphilmarshall** [comment]
Hi all: the reorganised version of the HIGHRESOLUTIONIMAGING repo is now visible here: https://github.com/tommasotreu/HIGHRESOLUTIONIMAGING/tree/reorg

If you like how this looks, and approve of the changes I have made in this PR thread, you can go ahead and merge the pull request. In that case, the new arxiv submission comment (with updated paper URL) would be as follows:


27 pages, 10 figures, to be submitted to JCAP. A full resolution, continuously updated version can be viewed at https://github.com/tommasotreu/HIGHRESOLUTIONIMAGING/blob/master/paper/High_resolution_imaging_requirements.pdf We invite comments and questions at https://github.com/tommasotreu/HIGHRESOLUTIONIMAGING/issues


Cheers

Phil

**Comment by aagnello** [comment]
Just one, very stupid question: what's the maximum length of "Comments" allowed by arxiv?

**Comment by drphilmarshall** [comment]
Not sure - but I think we'll be OK. I've done this before, at
http://arxiv.org/abs/1409.4291 - the URLs get rendered as the hyperlink
'this http url' which helps. Let's try it and see!

**Comment by aagnello** [comment]
Great, thanks. Also, shouldn't accuracy be mentioned alongside precision in the Readme?

**Comment by drphilmarshall** [comment]
I just pasted from the abstract!

**Pull request merged**
