### PR TITLE
Phil's edits

### PR DESCRIPTION
**Pull request by drphilmarshall**
Don't merge this yet, please - I'll make all my edits and then you can merge when I'm done (and when I've fixed all conflicts, too :-). This thread should show us all my commits, so you can follow along with the changes I am making (or suggesting).

### CODE REVIEW

**Comment by drphilmarshall** [comment]
PS. This PR supercedes issue #17, which I'll now close.

**Comment by drphilmarshall** [comment]
OK, I have been through the paper. I have a bunch of minor edits that I will make in the text directly, and I will also address the following 4 comments once we have discussed them on this thread:

* The source galaxies we use: are they good-enough approximations of QSO host galaxies? They seem quite compact, and I was a bit worried by the emphasis on using SLACS and SL2S systems as models in this particular regard.

* We could make the point that "faint systems" are *better* for TMT and JWST than are "bright" systems, because we won't be blinded by the point source.

* In the mock data generation description we refer to the survey telescopes' "maximum exposure times" whereas actually they have a fixed *exposure* time, and then some number of exposures. At this point we need to say how many exposures we are using. The LSST value of 4500s that appears later is for the 10-year stacked image (which explains why we are using the expected median image quality of 0.7"), but we should comment on this: in practice we might well be more interested in the 5 year best seeing stack (200s?), which will have a shorter effective exposure time but higher image quality (~0.5"?). See my final comment!

* We need to outline our "Further work", perhaps as part of a discussion section. I'd suggest that the next steps would be to 1) simulate a larger plausible sample, and look at the total (or if you prefer, mean) follow up costs (beyond the "first look" that we have carried out here), and 2) investigate the IFU data that we anticipate from TMT and JWST. Any guidance we can give here will be most helpful for whoever picks up this baton. A more extensive analysis of what the survey telescopes would provide across a large sample would be an important part of 1).

**Comment by drphilmarshall** [comment]
Ah yes, I also had a comment about the Figures 7-10 (the main results). Should we not be plotting 100% \cdot (\gamma'_{\rm out} - \gamma'_{\rm in}) / \gamma'_{\rm in}, with a gray band showing +/-2? The point as I understand it is to note that the points are consistent with zero (ie, we have not introduced systematic error during our emulation of the data analysis) and then to compare the error bars with 2%.  To do this, the error bars must represent the expected width of the marginalised posterior PDF Pr(\gamma'|data) (where expected means averaged over simulations). Is this what is plotted already? We should update the captions to make it clear how the "precision" is defined.

**Comment by tommasotreu** [comment]
Hi Phil, let's discuss all this stuff when we talk later today.

**Comment by tommasotreu** [comment]
Hi Phil, responding to some of your comments above:
1) I added words and references to the text explaining that agn hosts are typically brighter that what considered here, so we are being prudent. I think that's ok.
2) I think plotting out/in is the same as (out-in)/in. No need for XLM to remake the figures. What matters is the scatter, which is plotted as error bars. Not the bias.

**Pull request merged**
